#!/bin/bash
. ~/NumBox/utils/dialog.conf
# . ~/NumBox/utils/empty.sh 
nb_ver=$(cat ~/NumBox/.version)
back () { . ~/NumBox/Numbox;}
rmdir ~/NumBox/container/*/ &>/dev/null
rm -rf $TMPDIR/pulse-*
Dmenu_select=(1 "启动默认容器" 2 "启动快捷脚本" 3 "wine容器管理" 4 "NumBox插件" 5 "NumBox设置" 6 "关于NumBox" 7 "插件菜单")
Dmenu "NumBox" "触屏，键盘，鼠标以进行对话框操作" "${nb_ver}"
case $DMENU in
  1) 